apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: pg-dc
  namespace: pg-dc
spec:
  postgresVersion: 16

  instances:
    - name: instance1
      replicas: 2
      dataVolumeClaimSpec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi

  backups:
    pgbackrest:
      repos:
        - name: repo1
          s3:
            bucket: keen-pgbackrest-dc-2026
            endpoint: s3.us-east-1.amazonaws.com
            region: us-east-1
      global:
        repo1-path: /dc/pg-dc
        repo1-s3-key: <YOUR_S3_ACCESS_KEY>
        repo1-s3-key-secret: "<YOUR_S3_SECRET_KEY>"
        repo1-s3-region: us-east-1
